services:
  driver-base:
    image: cmucal/cabot-driver
    build:
      context: ./docker/driver
      additional_contexts:
        - src=./
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    environment:
      - ROS_LOG_DIR
      - CABOT_MODEL
      - CABOT_SIDE
      - CABOT_TOUCH_PARAMS
      - CABOT_ODRIVER_SERIAL_0
      - CABOT_ODRIVER_SERIAL_1
      - CABOT_IMU_ACCEL_BIAS
      - CABOT_IMU_GYRO_BIAS
      - RMW_IMPLEMENTATION
      - CYCLONEDDS_URI
      - CYCLONEDDS_NETWORK_INTERFACE_NAME
      - CYCLONEDDS_NETWORK_INTERFACE_AUTODETERMINE # set automatically by launch.sh
    volumes:
# device, bluetooth
      - /dev:/dev
      - /sys/devices:/sys/devices
      - /var/lib/bluetooth:/var/lib/bluetooth
      - /run/dbus:/run/dbus
      - /var/run/dbus:/var/run/dbus
# bridge - if DDS use shared memory
      - /dev/shm:/dev/shm
    privileged: true
    devices:
      - /dev/dri
    network_mode: host
    command:
      - "/launch.sh"
      - "-c"
      - "driver"

  driver-dev-base:
    extends:
      service: driver-base
    volumes:
# code from dependencies
      - ./cabot-common/cabot_common:/home/developer/driver_ws/src/cabot_common
      - ./cabot-common/cabot_msgs:/home/developer/driver_ws/src/cabot_msgs
      - ./cabot-common/docker/humble-custom/people:/home/developer/driver_ws/src/people
      - ./cabot-description/cabot_description:/home/developer/driver_ws/src/cabot_description
# code
      - ./cabot_base:/home/developer/driver_ws/src/cabot_base
      - ./cabot_serial:/home/developer/driver_ws/src/cabot_serial
      - ./motor_controller:/home/developer/driver_ws/src/motor_controller
      - ./wireless_scanner_ros:/home/developer/driver_ws/src/wireless_scanner_ros
      - ./script:/home/developer/driver_ws/script
  
  driver-prod-base:
    extends:
      service: driver-base

  wifi_scan-dev-base:
    extends:
      service: driver-dev-base
    command:
      - "/launch.sh"
      - "wifi-scan"

  wifi_scan-prod-base:
    extends:
      service: driver-prod-base
    command:
      - "/launch.sh"
      - "wifi-scan"

  ble_scan-dev-base:
    extends:
      service: driver-dev-base
    command:
      - "/launch.sh"
      - "ble-scan"

  ble_scan-prod-base:
    extends:
      service: driver-prod-base
    command:
      - "/launch.sh"
      - "ble-scan"
