services:
  driver-base:
    image: cmucal/cabot-driver:${CABOT_LAUNCH_IMAGE_TAG:-latest}
    build:
      context: ./docker/driver
      additional_contexts:
        - src=./
      args:
        - BASE_IMAGE=${BASE_IMAGE:-cabot-base}
      x-bake:
        tags:
          - ${REGISTRY:-cmucal}/cabot-driver
        platforms:
          - linux/amd64
          - linux/arm64
        output:
          - type=registry
    environment:
      - HOST_UID
      - HOST_GID
      - HOST_TZ
      - ROS_LOG_DIR
      - CABOT_MODEL
      - CABOT_SIDE
      - CABOT_TOUCH_PARAMS
      - CABOT_ODRIVER_SERIAL_0
      - CABOT_ODRIVER_SERIAL_1
      - CABOT_IMU_ACCEL_BIAS
      - CABOT_IMU_GYRO_BIAS
      - CABOT_USE_DIRECTIONAL_INDICATOR
      - CABOT_VIBRATOR_TYPE
      - CABOT_DEFAULT_MOTOR_CONTROL
      - RMW_IMPLEMENTATION
      - ROS_LOCALHOST_ONLY
      - ROS_DOMAIN_ID
      - CYCLONEDDS_URI
      - CYCLONEDDS_NETWORK_INTERFACE_NAME
      - CYCLONEDDS_NETWORK_INTERFACE_AUTODETERMINE # set automatically by launch.sh
      - ODRIVE_MODEL
      - ODRIVE_FIRMWARE_VERSION
    volumes:
# device, bluetooth
      - /dev:/dev
      - /sys/devices:/sys/devices
      - /var/lib/bluetooth:/var/lib/bluetooth
      - /run/dbus:/run/dbus
      - /var/run/dbus:/var/run/dbus
# bridge - if DDS use shared memory
      - /dev/shm:/dev/shm
    privileged: true
    devices:
      - /dev/dri
    network_mode: host
    command:
      - "/launch.sh"
      - "-c"
      - "driver"

  driver-dev-base:
    extends:
      service: driver-base
    volumes:
# code from dependencies
      - ./cabot-common/cabot_common:/home/developer/driver_ws/src/cabot_common
      - ./cabot-common/cabot_msgs:/home/developer/driver_ws/src/cabot_msgs
      - ./cabot-description/cabot_description:/home/developer/driver_ws/src/cabot_description
# code
      - ./cabot_base:/home/developer/driver_ws/src/cabot_base
      - ./cabot_serial:/home/developer/driver_ws/src/cabot_serial
      - ./cabot_can:/home/developer/driver_ws/src/cabot_can
      - ./motor_controller:/home/developer/driver_ws/src/motor_controller
      - ./power_controller:/home/developer/driver_ws/src/power_controller
      - ./wireless_scanner_ros:/home/developer/driver_ws/src/wireless_scanner_ros
      - ./script:/home/developer/driver_ws/script
      - ./uwbtag_interfaces:/home/developer/driver_ws/src/uwbtag_interfaces
      - ./uwbtag_publisher:/home/developer/driver_ws/src/uwbtag_publisher

  driver-dev:
    extends:
      service: driver-dev-base
    volumes:
      - ./docker/home:/home/developer/

  driver-prod-base:
    extends:
      service: driver-base

  driver-prod:
    extends:
      service: driver-prod-base
    volumes:
      - ./docker/home/.ros:/home/developer/.ros

  wifi_scan-dev-base:
    extends:
      service: driver-dev-base
    command:
      - "/launch.sh"
      - "wifi-scan"

  wifi_scan-dev:
    extends:
      service: wifi_scan-dev-base
    volumes:
      - ./docker/home:/home/developer/

  wifi_scan-prod-base:
    extends:
      service: driver-prod-base
    command:
      - "/launch.sh"
      - "wifi-scan"

  wifi_scan-prod:
    extends:
      service: wifi_scan-prod-base
    volumes:
      - ./docker/home/.ros:/home/developer/.ros

  ble_scan-dev-base:
    extends:
      service: driver-dev-base
    command:
      - "/launch.sh"
      - "ble-scan"

  ble_scan-dev:
    extends:
      service: ble_scan-dev-base
    volumes:
      - ./docker/home:/home/developer/

  ble_scan-prod-base:
    extends:
      service: driver-prod-base
    command:
      - "/launch.sh"
      - "ble-scan"

  ble_scan-prod:
    extends:
      service: ble_scan-prod-base
    volumes:
      - ./docker/home/.ros:/home/developer/.ros

  power_controller-base:
    environment:
      - CABOT_ACE_BATTERY_PORT
      - CABOT_ACE_BATTERY_BAUD
      - CABOT_ID_DIR=/home/developer/.ssh
      - CABOT_ID_FILE
    extends:
      service: driver-dev-base
    volumes:
# for systemctl
      - /run/systemd/system:/run/systemd/system
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /sys/fs/cgroup:/sys/fs/cgroup
# for jetson
      - ~/.ssh:/home/developer/.ssh
    command:
      - "/launch.sh"
      - "power"

  power_controller-dev:
    extends:
      service: power_controller-base
    volumes:
      - ./docker/home:/home/developer/

  power_controller-prod:
    extends:
      service: power_controller-base
    volumes:
      - ./docker/home/.ros:/home/developer/.ros
