services:
  # build
  driver:
    extends:
      file: docker-compose-base.yaml
      service: driver-dev
    profiles:
      - build

  # dev
  driver-dev:
    extends:
      file: docker-compose-base.yaml
      service: driver-dev
    profiles:
      - dev

  wifi_scan-dev:
    extends:
      file: docker-compose-base.yaml
      service: wifi_scan-dev
    profiles:
      - dev

  ble_scan-dev:
    extends:
      file: docker-compose-base.yaml
      service: ble_scan-dev
    profiles:
      - dev

  # prodimg
  driver-prod:
    extends:
      file: docker-compose-base.yaml
      service: driver-prod
    profiles:
      - prod

  wifi_scan-prod:
    extends:
      file: docker-compose-base.yaml
      service: wifi_scan-prod
    profiles:
      - prod

  ble_scan-prod:
    extends:
      file: docker-compose-base.yaml
      service: ble_scan-prod
    profiles:
      - prod

  # plugin
  power_controller-dev:
    extends:
      file: docker-compose-base.yaml
      service: power_controller-dev
    profiles:
      - plugin-dev

  power_controller-prod:
    extends:
      file: docker-compose-base.yaml
      service: power_controller-prod
    profiles:
      - plugin
