services:
  driver-base:
    build:
      context: ./docker/driver
    environment:
      - ROS_LOG_DIR
      - CABOT_MODEL
      - CABOT_SIDE
      - CABOT_TOUCH_PARAMS
      - CABOT_ODRIVER_SERIAL_0
      - CABOT_ODRIVER_SERIAL_1
      - CABOT_IMU_ACCEL_BIAS
      - CABOT_IMU_GYRO_BIAS
      - CABOT_USE_DIRECTIONAL_INDICATOR
      - RMW_IMPLEMENTATION
      - CYCLONEDDS_URI
      - CYCLONEDDS_NETWORK_INTERFACE_NAME
      - CYCLONEDDS_NETWORK_INTERFACE_AUTODETERMINE # set automatically by launch.sh
    volumes:
# device, bluetooth
      - /dev:/dev
      - /sys/devices:/sys/devices
      - /var/lib/bluetooth:/var/lib/bluetooth
      - /run/dbus:/run/dbus
      - /var/run/dbus:/var/run/dbus
# bridge - if DDS use shared memory
      - /dev/shm:/dev/shm
# code from dependencies
      - ./cabot-common/cabot_common:/home/developer/driver_ws/src/cabot_common
      - ./cabot-common/cabot_msgs:/home/developer/driver_ws/src/cabot_msgs
      - ./cabot-common/docker/humble-custom/people:/home/developer/driver_ws/src/people
      - ./cabot-description/cabot_description:/home/developer/driver_ws/src/cabot_description
# code
      - ./cabot_base:/home/developer/driver_ws/src/cabot_base
      - ./cabot_serial:/home/developer/driver_ws/src/cabot_serial
      - ./motor_controller:/home/developer/driver_ws/src/motor_controller
      - ./wireless_scanner_ros:/home/developer/driver_ws/src/wireless_scanner_ros
      - ./script:/home/developer/driver_ws/script
    privileged: true
    devices:
      - /dev/dri
    network_mode: host
    command:
      - "/launch.sh"
      - "-c"
      - "driver"

  wifi_scan-base:
    extends:
      service: driver-base
    command:
      - "/launch.sh"
      - "wifi-scan"

  ble_scan-base:
    extends:
      service: driver-base
    command:
      - "/launch.sh"
      - "ble-scan"
