# config file for cabot3-k1

pointcloud_to_laserscan_node:
  ros__parameters:
    # The LiDAR is mounted 90 degrees sideways.
    target_frame: lidar_base_link
    angle_min: -2.615  # -M_PI (back) + M_PI/6 (rear cover)
    angle_max:  2.615  #  M_PI (back) - M_PI/6 (rear cover)

# substitute these parameters to hesai/hesai_lidar.yaml
hesai_lidar:
  ros__parameters:
    lidar_type: "PandarXT-32"
    frame_id: "velodyne" # use velodyne for compatibility
    timestamp_type: "realtime"
    lidar_correction_file: "$(find-pkg-share hesai_lidar)/config/PandarXT-32.csv"

cabot:
  cabot_handle_v2_node:
    ros__parameters:
      no_vibration: false
      buttons:
        - BUTTON_UP
        - BUTTON_DOWN
        - BUTTON_LEFT
        - BUTTON_RIGHT

  cabot_handle_v3_node:
    ros__parameters:
      buttons:
        - BUTTON_UP
        - BUTTON_DOWN
        - BUTTON_LEFT
        - BUTTON_RIGHT

  cabot_serial:
    ros__parameters:
      port: /dev/ttyESP32

  odriver_adapter_node:
    ros__parameters:
      bias: 0.14 # same with cabot3-i1
      gain_omega: 0.0
      max_acc: 0.6

  cabot_can:
    ros__parameters:
      can_interface: can0
      # calibration_params: [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]

  features:
    ros__parameters:
      handleside: left,right
      touchmode: cap,tof,dual
